const galleryItems = [
    { id: 1, alt: "...", category: "human", image: "../img/human/1.jpg" },
    { id: 1, alt: "...", category: "human", image: "../img/human/2.jpg" },
    { id: 1, alt: "...", category: "human", image: "../img/human/3.jpg" },
    { id: 1, alt: "...", category: "human", image: "../img/human/4.jpg" },
    { id: 1, alt: "...", category: "human", image: "../img/human/5.jpg" },
    { id: 1, alt: "...", category: "human", image: "../img/human/6.jpg" },
    { id: 1, alt: "...", category: "human", image: "../img/human/7.jpg" },
    { id: 1, alt: "...", category: "human", image: "../img/human/8.jpg" },
    { id: 1, alt: "...", category: "nature", image: "../img/nature/1.jpg" },
    { id: 1, alt: "...", category: "nature", image: "../img/nature/2.jpg" },
    { id: 1, alt: "...", category: "nature", image: "../img/nature/3.jpg" },
    { id: 1, alt: "...", category: "nature", image: "../img/nature/4.jpg" },
    { id: 1, alt: "...", category: "nature", image: "../img/nature/5.jpg" },
    { id: 1, alt: "...", category: "nature", image: "../img/nature/6.jpg" },
    { id: 1, alt: "...", category: "nature", image: "../img/nature/7.jpg" },
    { id: 1, alt: "...", category: "nature", image: "../img/nature/8.jpg" },
    { id: 1, alt: "...", category: "pet", image: "../img/pet/1.jpg" },
    { id: 1, alt: "...", category: "pet", image: "../img/pet/2.jpg" },
    { id: 1, alt: "...", category: "pet", image: "../img/pet/3.jpg" },
    { id: 1, alt: "...", category: "pet", image: "../img/pet/4.jpg" },
    { id: 1, alt: "...", category: "pet", image: "../img/pet/5.jpg" },
    { id: 1, alt: "...", category: "pet", image: "../img/pet/6.jpg" },
    { id: 1, alt: "...", category: "pet", image: "../img/pet/7.jpg" },
    { id: 1, alt: "...", category: "pet", image: "../img/pet/8.jpg" },
    { id: 1, alt: "...", category: "place", image: "../img/place/1.jpg" },
    { id: 1, alt: "...", category: "place", image: "../img/place/2.jpg" },
    { id: 1, alt: "...", category: "place", image: "../img/place/3.jpg" },
    { id: 1, alt: "...", category: "place", image: "../img/place/4.jpg" },
    { id: 1, alt: "...", category: "place", image: "../img/place/5.jpg" },
    { id: 1, alt: "...", category: "place", image: "../img/place/6.jpg" },
    { id: 1, alt: "...", category: "place", image: "../img/place/7.jpg" },
    { id: 1, alt: "...", category: "place", image: "../img/place/8.jpg" },
    { id: 1, alt: "...", category: "place", image: "../img/place/9.jpg" },
    { id: 1, alt: "...", category: "place", image: "../img/place/10.jpg" },
];

export default galleryItems;