const galleryItems = [
    { id: 1, alt: "...", category: "human", image: "../public/img/human/1.jpg" },
    { id: 1, alt: "...", category: "human", image: "../public/img/human/3.jpg" },
    { id: 2, alt: "...", category: "human", image: "../public/img/human/4.jpg" },
    { id: 3, alt: "...", category: "human", image: "../public/img/human/5.jpg" },
    { id: 4, alt: "...", category: "human", image: "../public/img/human/6.jpg" },
    { id: 5, alt: "...", category: "human", image: "../public/img/human/7.jpg" },
    { id: 6, alt: "...", category: "human", image: "../public/img/human/8.jpg" },
    { id: 7, alt: "...", category: "nature", image: "../public/img/nature/1.jpg" },
    { id: 8, alt: "...", category: "nature", image: "../public/img/nature/2.jpg" },
    { id: 9, alt: "...", category: "nature", image: "../public/img/nature/3.jpg" },
    { id: 10, alt: "...", category: "nature", image: "../public/img/nature/4.jpg" },
    { id: 11, alt: "...", category: "nature", image: "../public/img/nature/5.jpg" },
    { id: 12, alt: "...", category: "nature", image: "../public/img/nature/6.jpg" },
    { id: 13, alt: "...", category: "nature", image: "../public/img/nature/7.jpg" },
    { id: 14, alt: "...", category: "nature", image: "../public/img/nature/8.jpg" },
    { id: 15, alt: "...", category: "pet", image: "../public/img/pet/1.jpg" },
    { id: 16, alt: "...", category: "pet", image: "../public/img/pet/2.jpg" },
    { id: 17, alt: "...", category: "pet", image: "../public/img/pet/3.jpg" },
    { id: 18, alt: "...", category: "pet", image: "../public/img/pet/4.jpg" },
    { id: 19, alt: "...", category: "pet", image: "../public/img/pet/5.jpg" },
    { id: 20, alt: "...", category: "pet", image: "../public/img/pet/6.jpg" },
    { id: 21, alt: "...", category: "pet", image: "../public/img/pet/7.jpg" },
    { id: 22, alt: "...", category: "pet", image: "../public/img/pet/8.jpg" },
    { id: 23, alt: "...", category: "place", image: "../public/img/place/1.jpg" },
    { id: 24, alt: "...", category: "place", image: "../public/img/place/2.jpg" },
    { id: 25, alt: "...", category: "place", image: "../public/img/place/3.jpg" },
    { id: 26, alt: "...", category: "place", image: "../public/img/place/4.jpg" },
    { id: 27, alt: "...", category: "place", image: "../public/img/place/5.jpg" },
    { id: 28, alt: "...", category: "place", image: "../public/img/place/6.jpg" },
    { id: 29, alt: "...", category: "place", image: "../public/img/place/7.jpg" },
    { id: 30, alt: "...", category: "place", image: "../public/img/place/8.jpg" },
    { id: 31, alt: "...", category: "place", image: "../public/img/place/9.jpg" },
    { id: 32, alt: "...", category: "place", image: "../public/img/place/10.jpg" },
    { id: 33, alt: "...", category: "human", image: "../public/img/human/2.jpg" },
]

export default galleryItems;